{$IfNDef FlowUtilties_Included}
{$Define FlowUtilties_Included}

{ Copyright Fusion Factory Pty Ltd 2017}

const System_Security_Cryptography_CipherMode_CBC = 1;
const System_Security_Cryptography_CipherMode_ECB = 2;
const System_Security_Cryptography_CipherMode_OFB = 3;
const System_Security_Cryptography_CipherMode_CFB = 4;
const System_Security_Cryptography_CipherMode_CTS = 5;

const System_Security_Cryptography_PaddingMode_None = 1;
const System_Security_Cryptography_PaddingMode_PKCS7 = 2;
const System_Security_Cryptography_PaddingMode_Zeros = 3;
const System_Security_Cryptography_PaddingMode_ANSIX923 = 4;
const System_Security_Cryptography_PaddingMode_ISO10126 = 5;

{$EndIf}
